server:
  port: 3000
spring:
  application:
    name: crowd-file
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
# 项目相关配置
file-service:
  # 文件路径
  profile: E:/HeadlinesFiles/